### PR TITLE
Bugfix/rbac implement boundedvec

### PR DESCRIPTION
**Pull request by talhadaar**
Integrating changes from Rbac after introducing BoundedVec into it.

### CODE REVIEW

**Comment by sfffaaa** [comment]
Please fix the check and then we should discuss the limitation with others

**Comment by talhadaar** [comment]
> Please fix the check and then we should discuss the limitation with others

The 'cargo test --release' step fails because RBAC's deps in this PR are pointing to 'dev' branch on peaq-pallet-rbac repo, where the concerned changes have not yet merged from [this pr](https://github.com/peaqnetwork/peaq-pallet-rbac/pull/23)

**Review by sfffaaa — APPROVED** [review]

**Comment by talhadaar** [comment]
@sfffaaa Hey Jay, I updated the max bounds of the BoundedVec, are these correct?

**Comment by talhadaar** [comment]
> @sfffaaa Hey Jay, I updated the max bounds of the BoundedVec, are these correct?

Currently leaving these bounds as they are, as I want to benchmark and read more on using u32::MAX, but can't find much information on it.

**Pull request merged**
